#!/usr/bin/env groovy

node {
    stage 'prepare env'
    env.WORKSPACE = pwd()
    def home = "${env.WORKSPACE}"

    stage('checkout') {
        checkout scm
    }

    stage("execute playbook ") {
        sh """
            ansible-playbook --private-key ~/.ssh/delphoi.pem "${home}/ansible/locust-ec2.yaml"
        """
    }
}