master:
  image: locust:latest
  command: --host=http://www.google.com/ --master
  hostname: master
  mem_limit: 1G
  ports:
    - 8089:8089

slave1:
  image: locust:latest
  command: --host=http://www.google.com/ --slave --master-host=master
  hostname: slave
  mem_limit: 2G
  links:
    - master

slave2:
  image: locust:latest
  command: --host=http://www.google.com/ --slave --master-host=master
  hostname: slave
  mem_limit: 2G
  links:
    - master

slave3:
  image: locust:latest
  command: --host=http://www.google.com/ --slave --master-host=master
  hostname: slave
  mem_limit: 2G
  links:
    - master
 