- hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Get Ecr Token
      shell: aws ecr get-login --no-include-email --region eu-west-1
      register: dockerToken

    - name: Execute Token
      command: "{{ dockerToken.stdout }}"